'use strict';

const COMMAND_ACTION_TYPES = Object.freeze({
  CLEAR_MESSAGES: 'clear_messages',
  TICKET_PANEL: 'ticket_panel',
  BAN_MEMBER: 'ban_member',
  KICK_MEMBER: 'kick_member',
  TIMEOUT_MEMBER: 'timeout_member',
  UNTIMEOUT_MEMBER: 'untimeout_member',
  WARN_MEMBER: 'warn_member',
});

const SUPPORTED_NATIVE_ACTIONS = new Set(Object.values(COMMAND_ACTION_TYPES));

const DEFAULT_SYSTEM_COMMANDS = Object.freeze([
  {
    system_key: 'moderation_ban',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'ban',
    description: 'Bannit un membre avec raison',
    response: 'Bannit un membre du serveur avec raison et journalise l action.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#ef4444',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 2500,
    usage_hint: '/ban utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.BAN_MEMBER,
    action_config: {
      log_channel_id: '',
      dm_user: 1,
      require_reason: 1,
      delete_message_seconds: 0,
      success_visibility: 'ephemeral',
    },
  },
  {
    system_key: 'moderation_kick',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'kick',
    description: 'Expulse un membre avec raison',
    response: 'Expulse un membre du serveur avec raison et journalise l action.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#f97316',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 2500,
    usage_hint: '/kick utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.KICK_MEMBER,
    action_config: {
      log_channel_id: '',
      dm_user: 1,
      require_reason: 1,
      success_visibility: 'ephemeral',
    },
  },
  {
    system_key: 'moderation_timeout',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'tempmute',
    description: 'Met un membre en mute temporaire',
    response: 'Applique un timeout a un membre avec duree et raison.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#f59e0b',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 2500,
    usage_hint: '/tempmute utilisateur:@membre duree:10m raison:"..."',
    action_type: COMMAND_ACTION_TYPES.TIMEOUT_MEMBER,
    action_config: {
      log_channel_id: '',
      dm_user: 1,
      require_reason: 1,
      default_duration_ms: 600000,
      success_visibility: 'ephemeral',
    },
  },
  {
    system_key: 'moderation_untimeout',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'unmute',
    description: 'Retire le mute temporaire d un membre',
    response: 'Retire le timeout d un membre et journalise l action.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#22c55e',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 1500,
    usage_hint: '/unmute utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.UNTIMEOUT_MEMBER,
    action_config: {
      log_channel_id: '',
      dm_user: 0,
      require_reason: 0,
      success_visibility: 'ephemeral',
    },
  },
  {
    system_key: 'moderation_warn',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'warn',
    description: 'Ajoute un avertissement a un membre',
    response: 'Ajoute un avertissement avec raison et journalise l action.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#eab308',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 1500,
    usage_hint: '/warn utilisateur:@membre raison:"..." points:1',
    action_type: COMMAND_ACTION_TYPES.WARN_MEMBER,
    action_config: {
      log_channel_id: '',
      dm_user: 1,
      require_reason: 1,
      default_points: 1,
      success_visibility: 'ephemeral',
    },
  },
  {
    system_key: 'moderation_clear',
    category: 'moderation',
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name: 'clear',
    description: 'Supprime un lot de messages',
    response: 'Supprime un nombre precis de messages dans le salon courant.',
    response_mode: 'reply',
    embed_enabled: false,
    embed_title: '',
    embed_color: '#22d3ee',
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms: 2500,
    usage_hint: '/clear amount:20',
    action_type: COMMAND_ACTION_TYPES.CLEAR_MESSAGES,
    action_config: {
      log_channel_id: '',
      min_amount: 1,
      max_amount: 100,
      default_amount: 20,
      success_message: '{count} messages supprimes dans {channel}.',
      empty_message: 'Aucun message recent a supprimer ici.',
      denied_message: 'Tu dois avoir la permission de gerer les messages pour utiliser cette commande.',
      success_visibility: 'ephemeral',
    },
  },
]);

module.exports = {
  COMMAND_ACTION_TYPES,
  SUPPORTED_NATIVE_ACTIONS,
  DEFAULT_SYSTEM_COMMANDS,
};
