'use strict';

const COMMAND_ACTION_TYPES = Object.freeze({
  CLEAR_MESSAGES: 'clear_messages',
  TICKET_PANEL: 'ticket_panel',
  BAN_MEMBER: 'ban_member',
  BLACKLIST_MEMBER: 'blacklist_member',
  KICK_MEMBER: 'kick_member',
  SOFTBAN_MEMBER: 'softban_member',
  TIMEOUT_MEMBER: 'timeout_member',
  UNTIMEOUT_MEMBER: 'untimeout_member',
  WARN_MEMBER: 'warn_member',
  UNBAN_MEMBER: 'unban_member',
  UNBLACKLIST_MEMBER: 'unblacklist_member',
  ADD_ROLE: 'add_role',
  REMOVE_ROLE: 'remove_role',
  SET_NICKNAME: 'set_nickname',
  LOCK_CHANNEL: 'lock_channel',
  UNLOCK_CHANNEL: 'unlock_channel',
  SLOWMODE_CHANNEL: 'slowmode_channel',
  SAY_MESSAGE: 'say_message',
  ANNOUNCE_MESSAGE: 'announce_message',
  MOVE_MEMBER: 'move_member',
  DISCONNECT_MEMBER: 'disconnect_member',
  PING_INFO: 'ping_info',
  BOT_INFO: 'bot_info',
  SERVER_INFO: 'server_info',
  MEMBERCOUNT_INFO: 'membercount_info',
  USER_INFO: 'user_info',
  AVATAR_INFO: 'avatar_info',
  BANNER_INFO: 'banner_info',
  ROLE_INFO: 'role_info',
  CHANNEL_INFO: 'channel_info',
  JOINED_AT_INFO: 'joined_at_info',
});

function createSystemCommand({
  system_key,
  category = 'moderation',
  command_name,
  description,
  response,
  embed_color,
  usage_hint,
  action_type,
  action_config,
  cooldown_ms = 1500,
  response_mode = 'reply',
  embed_enabled = false,
  embed_title = '',
}) {
  return {
    system_key,
    category,
    enabled: 1,
    command_type: 'slash',
    command_prefix: '/',
    command_name,
    description,
    response,
    response_mode,
    embed_enabled,
    embed_title,
    embed_color,
    mention_user: false,
    require_args: false,
    delete_trigger: false,
    cooldown_ms,
    usage_hint,
    action_type,
    action_config,
  };
}

const moderationAuditConfig = Object.freeze({
  log_channel_id: '',
  require_reason: 1,
  success_visibility: 'ephemeral',
});

const defaultChannelConfig = Object.freeze({
  log_channel_id: '',
  default_channel_id: '',
  success_visibility: 'ephemeral',
});

const infoCommandConfig = Object.freeze({
  success_visibility: 'ephemeral',
});

const DEFAULT_SYSTEM_COMMANDS = Object.freeze([
  createSystemCommand({
    system_key: 'moderation_ban',
    command_name: 'ban',
    description: 'Bannit un membre avec raison',
    response: 'Bannit un membre du serveur avec raison et journalise l action.',
    embed_color: '#ef4444',
    usage_hint: '/ban utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.BAN_MEMBER,
    cooldown_ms: 2500,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
      delete_message_seconds: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_kick',
    command_name: 'kick',
    description: 'Expulse un membre avec raison',
    response: 'Expulse un membre du serveur avec raison et journalise l action.',
    embed_color: '#f97316',
    usage_hint: '/kick utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.KICK_MEMBER,
    cooldown_ms: 2500,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_blacklist',
    command_name: 'blacklist',
    description: 'Blacklist un membre sur tout le reseau',
    response: 'Bannit le membre ici et l ajoute a la blacklist reseau du bot.',
    embed_color: '#dc2626',
    usage_hint: '/blacklist utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.BLACKLIST_MEMBER,
    cooldown_ms: 3000,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
      delete_message_seconds: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_softban',
    command_name: 'softban',
    description: 'Ban puis deban un membre pour nettoyer',
    response: 'Bannit puis debannit un membre pour nettoyer ses messages recents.',
    embed_color: '#fb7185',
    usage_hint: '/softban utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.SOFTBAN_MEMBER,
    cooldown_ms: 3000,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
      delete_message_seconds: 86400,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_timeout',
    command_name: 'tempmute',
    description: 'Met un membre en mute temporaire',
    response: 'Applique un timeout a un membre avec duree et raison.',
    embed_color: '#f59e0b',
    usage_hint: '/tempmute utilisateur:@membre duree:10m raison:"..."',
    action_type: COMMAND_ACTION_TYPES.TIMEOUT_MEMBER,
    cooldown_ms: 2500,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
      default_duration_ms: 600000,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_untimeout',
    command_name: 'unmute',
    description: 'Retire le mute temporaire d un membre',
    response: 'Retire le timeout d un membre et journalise l action.',
    embed_color: '#22c55e',
    usage_hint: '/unmute utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.UNTIMEOUT_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 0,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_warn',
    command_name: 'warn',
    description: 'Ajoute un avertissement a un membre',
    response: 'Ajoute un avertissement avec raison et journalise l action.',
    embed_color: '#eab308',
    usage_hint: '/warn utilisateur:@membre raison:"..." points:1',
    action_type: COMMAND_ACTION_TYPES.WARN_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      dm_user: 1,
      default_points: 1,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_clear',
    command_name: 'clear',
    description: 'Supprime un lot de messages',
    response: 'Supprime un nombre precis de messages dans le salon courant.',
    embed_color: '#22d3ee',
    usage_hint: '/clear amount:20',
    action_type: COMMAND_ACTION_TYPES.CLEAR_MESSAGES,
    cooldown_ms: 2500,
    action_config: {
      log_channel_id: '',
      min_amount: 1,
      max_amount: 100,
      success_message: '{count} messages supprimes dans {channel}.',
      empty_message: 'Aucun message recent a supprimer ici.',
      denied_message: 'Tu dois avoir la permission de gerer les messages pour utiliser cette commande.',
      success_visibility: 'ephemeral',
    },
  }),
  createSystemCommand({
    system_key: 'moderation_unban',
    command_name: 'unban',
    description: 'Retire le ban d un utilisateur',
    response: 'Retire le bannissement d un utilisateur via son ID Discord.',
    embed_color: '#22c55e',
    usage_hint: '/unban user_id:123456789012345678 raison:"..."',
    action_type: COMMAND_ACTION_TYPES.UNBAN_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_unblacklist',
    command_name: 'unblacklist',
    description: 'Retire un utilisateur de la blacklist reseau',
    response: 'Retire un utilisateur de la blacklist reseau sans toucher aux bans actifs.',
    embed_color: '#10b981',
    usage_hint: '/unblacklist user_id:123456789012345678 raison:"..."',
    action_type: COMMAND_ACTION_TYPES.UNBLACKLIST_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_add_role',
    command_name: 'addrole',
    description: 'Ajoute un role a un membre',
    response: 'Ajoute un role au membre cible avec journalisation.',
    embed_color: '#60a5fa',
    usage_hint: '/addrole utilisateur:@membre role:@role raison:"..."',
    action_type: COMMAND_ACTION_TYPES.ADD_ROLE,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_remove_role',
    command_name: 'removerole',
    description: 'Retire un role a un membre',
    response: 'Retire un role au membre cible avec journalisation.',
    embed_color: '#38bdf8',
    usage_hint: '/removerole utilisateur:@membre role:@role raison:"..."',
    action_type: COMMAND_ACTION_TYPES.REMOVE_ROLE,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_nickname',
    command_name: 'nick',
    description: 'Change le pseudo d un membre',
    response: 'Met a jour le pseudo d un membre avec trace en logs.',
    embed_color: '#a78bfa',
    usage_hint: '/nick utilisateur:@membre nickname:"Nouveau pseudo" raison:"..."',
    action_type: COMMAND_ACTION_TYPES.SET_NICKNAME,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_lock',
    command_name: 'lock',
    description: 'Verrouille un salon texte',
    response: 'Verrouille un salon texte pour bloquer l envoi de messages.',
    embed_color: '#f97316',
    usage_hint: '/lock salon:#general raison:"..."',
    action_type: COMMAND_ACTION_TYPES.LOCK_CHANNEL,
    action_config: {
      ...defaultChannelConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_unlock',
    command_name: 'unlock',
    description: 'Deverrouille un salon texte',
    response: 'Retire le verrouillage d un salon texte.',
    embed_color: '#22c55e',
    usage_hint: '/unlock salon:#general raison:"..."',
    action_type: COMMAND_ACTION_TYPES.UNLOCK_CHANNEL,
    action_config: {
      ...defaultChannelConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_slowmode',
    command_name: 'slowmode',
    description: 'Regle le mode lent d un salon',
    response: 'Ajuste le slowmode du salon cible en quelques secondes.',
    embed_color: '#f59e0b',
    usage_hint: '/slowmode salon:#general secondes:30 raison:"..."',
    action_type: COMMAND_ACTION_TYPES.SLOWMODE_CHANNEL,
    action_config: {
      ...defaultChannelConfig,
      require_reason: 0,
      default_seconds: 30,
    },
  }),
  createSystemCommand({
    system_key: 'utility_say',
    category: 'utility',
    command_name: 'say',
    description: 'Fait parler le bot dans un salon',
    response: 'Publie un message brut dans le salon choisi.',
    embed_color: '#06b6d4',
    usage_hint: '/say salon:#annonces message:"..."',
    action_type: COMMAND_ACTION_TYPES.SAY_MESSAGE,
    action_config: {
      ...defaultChannelConfig,
      allow_mentions: 0,
    },
  }),
  createSystemCommand({
    system_key: 'utility_announce',
    category: 'utility',
    command_name: 'announce',
    description: 'Publie une annonce propre en embed',
    response: 'Publie une annonce avec titre, contenu et journalisation.',
    embed_color: '#8b5cf6',
    usage_hint: '/announce salon:#annonces titre:"Annonce" message:"..."',
    action_type: COMMAND_ACTION_TYPES.ANNOUNCE_MESSAGE,
    embed_enabled: true,
    embed_title: 'Annonce',
    action_config: {
      ...defaultChannelConfig,
      ping_everyone: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_move',
    command_name: 'move',
    description: 'Deplace un membre vers un vocal',
    response: 'Deplace un membre connecte vers un autre salon vocal.',
    embed_color: '#14b8a6',
    usage_hint: '/move utilisateur:@membre salon:Vocal raison:"..."',
    action_type: COMMAND_ACTION_TYPES.MOVE_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'moderation_disconnect',
    command_name: 'disconnect',
    description: 'Deconnecte un membre de son vocal',
    response: 'Deconnecte un membre de son salon vocal avec journalisation.',
    embed_color: '#0ea5e9',
    usage_hint: '/disconnect utilisateur:@membre raison:"..."',
    action_type: COMMAND_ACTION_TYPES.DISCONNECT_MEMBER,
    action_config: {
      ...moderationAuditConfig,
      require_reason: 0,
    },
  }),
  createSystemCommand({
    system_key: 'utility_ping',
    category: 'utility',
    command_name: 'ping',
    description: 'Affiche la latence du bot',
    response: 'Affiche le ping du bot et de l API Discord.',
    embed_color: '#22d3ee',
    usage_hint: '/ping',
    action_type: COMMAND_ACTION_TYPES.PING_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_botinfo',
    category: 'utility',
    command_name: 'botinfo',
    description: 'Resume le statut du bot',
    response: 'Affiche les informations publiques du bot sur ce serveur.',
    embed_color: '#8b5cf6',
    usage_hint: '/botinfo',
    action_type: COMMAND_ACTION_TYPES.BOT_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_serverinfo',
    category: 'utility',
    command_name: 'serverinfo',
    description: 'Affiche les infos du serveur',
    response: 'Resume les informations principales du serveur Discord.',
    embed_color: '#38bdf8',
    usage_hint: '/serverinfo',
    action_type: COMMAND_ACTION_TYPES.SERVER_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_membercount',
    category: 'utility',
    command_name: 'membercount',
    description: 'Compte les membres du serveur',
    response: 'Affiche le nombre total de membres et de bots.',
    embed_color: '#14b8a6',
    usage_hint: '/membercount',
    action_type: COMMAND_ACTION_TYPES.MEMBERCOUNT_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_userinfo',
    category: 'utility',
    command_name: 'userinfo',
    description: 'Affiche les infos publiques d un membre',
    response: 'Affiche le profil public, les roles et les dates utiles du membre.',
    embed_color: '#60a5fa',
    usage_hint: '/userinfo utilisateur:@membre',
    action_type: COMMAND_ACTION_TYPES.USER_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_avatar',
    category: 'utility',
    command_name: 'avatar',
    description: 'Affiche l avatar d un membre',
    response: 'Affiche l avatar du membre cible en grand format.',
    embed_color: '#a78bfa',
    usage_hint: '/avatar utilisateur:@membre',
    action_type: COMMAND_ACTION_TYPES.AVATAR_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_banner',
    category: 'utility',
    command_name: 'banner',
    description: 'Affiche la banniere d un membre',
    response: 'Affiche la banniere du membre si elle existe.',
    embed_color: '#f472b6',
    usage_hint: '/banner utilisateur:@membre',
    action_type: COMMAND_ACTION_TYPES.BANNER_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_roleinfo',
    category: 'utility',
    command_name: 'roleinfo',
    description: 'Affiche les infos d un role',
    response: 'Affiche la couleur, la position et le nombre de membres du role.',
    embed_color: '#f59e0b',
    usage_hint: '/roleinfo role:@role',
    action_type: COMMAND_ACTION_TYPES.ROLE_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_channelinfo',
    category: 'utility',
    command_name: 'channelinfo',
    description: 'Affiche les infos d un salon',
    response: 'Affiche le type, la categorie et les reglages visibles du salon.',
    embed_color: '#10b981',
    usage_hint: '/channelinfo salon:#general',
    action_type: COMMAND_ACTION_TYPES.CHANNEL_INFO,
    action_config: infoCommandConfig,
  }),
  createSystemCommand({
    system_key: 'utility_joinedat',
    category: 'utility',
    command_name: 'joinedat',
    description: 'Affiche la date d arrivee d un membre',
    response: 'Affiche depuis quand le membre a rejoint le serveur.',
    embed_color: '#06b6d4',
    usage_hint: '/joinedat utilisateur:@membre',
    action_type: COMMAND_ACTION_TYPES.JOINED_AT_INFO,
    action_config: infoCommandConfig,
  }),
]);

const SUPPORTED_NATIVE_ACTIONS = new Set(Object.values(COMMAND_ACTION_TYPES));

module.exports = {
  COMMAND_ACTION_TYPES,
  SUPPORTED_NATIVE_ACTIONS,
  DEFAULT_SYSTEM_COMMANDS,
};
